#!/usr/bin/env bash
#
# This projet is too simple to need any bash scripts,
# but it might one day.

# Haiku to dog-fooding
#
# My eyes are dry
# But I have the tools I need
# And no real work got done

# Build and install locally, in "${HOME}/.local/bin"
# Needs sudo.
install() {
    # cargo clean
    cargo build --release
    rm "${HOME}/.local/bin/lk"
    cp target/release/lk "${HOME}/.local/bin"
}
