name: Rust

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --test-threads=1
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Release binaries
        uses: rust-build/rust-build.action@v1.2.1
